# Generated by Django 4.1.4 on 2023-01-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageDetect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(unique=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CheckList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(default=None, max_length=200, unique=True),
                ),
                ("answer", models.BooleanField(null=True)),
                ("bigo", models.CharField(blank=True, default="", max_length=100)),
                (
                    "title",
                    models.ForeignKey(
                        db_column="title",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.type",
                    ),
                ),
            ],
        ),
    ]
