# Generated by Django 4.1.4 on 2023-01-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="ImageDetect",),
    ]
