# Generated by Django 4.1.4 on 2023-01-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_delete_imagedetect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageDetect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(unique=True, upload_to="")),
            ],
        ),
    ]
