# Generated by Django 4.1.4 on 2023-01-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_imagedetect"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.ForeignKey(
                        db_column="title",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.checklist",
                    ),
                ),
            ],
        ),
    ]
