# Generated by Django 4.1.4 on 2023-01-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="title",
            field=models.ForeignKey(
                db_column="title",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.type",
            ),
        ),
    ]
