# Generated by Django 4.1.4 on 2023-01-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_history_title"),
    ]

    operations = [
        migrations.DeleteModel(name="History",),
    ]
