# Generated by Django 4.1.4 on 2023-01-26 16:59

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_alter_imagedetect_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagedetect",
            name="image",
            field=models.ImageField(
                storage=backend.models.OverwriteStorage, upload_to="yolov5/images"
            ),
        ),
    ]
